/**
 * Optional localized display name overrides for models.
 *
 * Keyed by normalized model id (use forward slashes for paths).
 * Example:
 * {
 *   'CHA_Alf_SSR_01': { en: 'Alf', kr: '알프' },
 *   'StellarSora/assets/.../10301_L': { en: 'Unit 10301 L', kr: '10301 L' },
 * }
 */
export const ModelNameOverrides: Record<string, Record<string, string>> = {
  // Add overrides here as needed.
  '5maqiduo/CHA_Bibi_NPC_01': { zh: '小哔', en: 'Beepy' },
  '26weierde/CHA_V3_01': { zh: 'V3机器人', en: 'V3 Robot' },
  '5maqiduo/CHA_Bibi_NPC_02': { zh: '小哔原型', en: 'Beepy Prototype' },
  '13chuntian/CHA_Bibi_NPC_03': { zh: '小哔丹德莱', en: 'Dandegate' },
  '21aifu/greencat': { zh: '格琳喵', en: 'Kalinyan' },
  '31.5suopu/CHA_SopModJr_01': { zh: 'JR', en: 'JR' },
  '0ob/CHA_Berser_NPC_01': { zh: '布瑟尔', en: 'Berserl' },
  '0ob/CHA_Inspector_NPC_01': { zh: '检察员', en: 'Inspector' },
  '0ob/CHA_Lieutenant_NPC_01': { zh: '驻军中尉', en: 'Garrison Lieutenant' },
  '0ob/CHA_Consignor_NPC_01': { zh: '委托人', en: 'Client' },
  '0ob/CHA_Ussery_NPC_01': { zh: '厄舍上尉', en: 'Captain Ussery' },
  '0ob/CHA_Vladimir_NPC_01': { zh: '弗拉基米尔准尉', en: 'Warrant Officer Vladimir' },
  '2sangduolaixi/CHA_Unitas_NPC_01': { zh: '帕拉蒂斯徒从', en: 'Paradeus Follower' },
  '2sangduolaixi/CHA_Unitas_NPC_02': { zh: '年轻帕拉蒂斯徒从', en: 'Paradeus Follower Young' },
  '0ob/CHA_Crifium_NPC_01': { zh: '赫瑞尤', en: 'Crifium' },
  '1daiyan/CHA_RNDmale_NPC_01': { zh: '男性路人', en: 'Male Passerby' },
  '1daiyan/CHA_RNDmale_NPC_02': { zh: '男性路人戴帽子', en: 'Male Passerby Hat' },
  '5maqiduo/CHA_Farkas_NPC_01': { zh: '佛尔卡什', en: 'Farkas' },
  '1daiyan/CHA_Flagg_NPC_01': { zh: '弗拉格', en: 'Flagg' },
  '9kelukai/CHA_Dmitriy_NPC_01': { zh: '德米特里年长', en: 'Dmitry' },
  '9.5mishiti/CHA_Dmitriy_Young_NPC': { zh: '德米特里年轻', en: 'Dmitry Young' },
  '9kelukai/CHA_Soldier01_NPC_01': { zh: '勘测部队士兵A', en: 'Survey Corps Soldier A' },
  '9kelukai/CHA_Soldier01_NPC_02': { zh: '勘测部队士兵B', en: 'Survey Corps Soldier B' },
  '9kelukai/CHA_Liaison_NPC_01': { zh: '勘测部队联络员', en: 'Survey Corps Liaison Officer' },
  '9kelukai/CHA_Loring_NPC_01': { zh: '洛林', en: 'Larion' },
  '9.5mishiti/CHA_Ivan_NPC_01': { zh: '伊万', en: 'Ivan' },
  '9kelukai/CHA_Deele_NPC_01': { zh: '德尔', en: 'Dier' },
  '9.5mishiti/CHA_Nikolay_NPC_01': { zh: '尼古拉', en: 'Nikolai' },
  '9.5mishiti/CHA_MysteryMan_NPC_01': { zh: '神秘人', en: 'Mysterious Man' },
  '31.5suopu/CHA_MysteryMan_NPC_02': { zh: '神秘人2', en: 'Mysterious Man 2' },
  '9.5mishiti/CHA_MangiEmployee_NPC_01': { zh: '曼尼安保成员', en: 'Mangi Security Member' },
  '15youxi/CHA_Bowen_NPC_01': { zh: '波文', en: 'Bowen' },
  '13.5peili/CHA_AnshangQ_NPC_01': { zh: '雅各布', en: 'Jakub' },
  '14qiuhua/CHA_CensorLeo_NPC_01': { zh: '监察官雷欧', en: 'Inspector Leo' },
  '14qiuhua/CHA_CaptainKellen_NPC_01': { zh: '远征队长凯伦', en: 'Expedition Leader Garen' },
  '14qiuhua/CHA_MangiKnellA_NPC_01': { zh: '噩兆小队A', en: 'Omen Squad A' },
  '14qiuhua/CHA_MangiKnellB_NPC_01': { zh: '噩兆小队B', en: 'Omen Squad B' },
  '14qiuhua/CHA_MangiKnellC_NPC_01': { zh: '噩兆小队C', en: 'Omen Squad C' },
  '14qiuhua/CHA_MangiKnellD_NPC_01': { zh: '噩兆小队D', en: 'Omen Squad D' },
  '16nijita/CHA_Davey_NPC_01': { zh: '戴维', en: 'David' },
  '16nijita/CHA_Green_RichMale01_NPC_01': { zh: '白区男性', en: 'White Zone Man' },
  '16nijita/CHA_Green_NormalMale01_NPC_01': { zh: '绿区男性', en: 'Green Zone Man' },
  '16nijita/CHA_Yellow_NormalMale01_NPC_01': { zh: '黄区男性', en: 'Yellow Zone Man' },
  '17laiya/CHA_Fadei_NPC_01': { zh: '斐狄', en: 'Fedya' },
  '17laiya/CHA_Rurik_NPC_01': { zh: '留里克', en: 'Rurik' },
  '17laiya/CHA_Zimmermann_NPC_01': { zh: '齐默尔曼', en: 'Zimmerman' },
  '17.5luobeila/CHA_Zimmermann_NPC_02': { zh: '齐默尔曼（里）', en: 'Zimmerman（里）' },
  '17.5luobeila/CHA_Pavel_NPC_01': { zh: '巴维尔', en: 'Pavel（巴维尔）' },
  '20linde/CHA_Karl_NPC_01': { zh: '卡尔', en: 'Karl' },
  '20linde/CHA_Yakov_NPC_01': { zh: '雅科夫', en: 'Yakov' },
  '20linde/CHA_Lonnie_NPC_01': { zh: '朗尼', en: 'Lonnie' },
  '21aifu/CHA_URNCofficer_NPC_01': { zh: '军方代表', en: 'URNC Officer' },
  '21aifu/CHA_Kryuger_NPC_01': { zh: '克鲁格', en: 'Kryuger' },
  '21aifu/CHA_6P62_BOSS_01': { zh: '6P62BOSS', en: '6P62 Boss' },
  '27luoleilai/CHA_6P62_xinyuanguaidao_01': { zh: '6P62怪盗', en: '6P62 Phantom Thief' },
  '21.5weimaxina/CHA_Griffin_NPC_01': { zh: '爵士', en: 'Earl' },
  '21.5weimaxina/CHA_Havier_NPC_01': { zh: '哈维尔', en: 'Havier' },
  '21.5weimaxina/CHA_Olek_NPC_01': { zh: '奥列克', en: 'Olek' },
  '24hailun/CHA_Konny_NPC_01': { zh: '柯尼', en: 'Kenny' },
  '25yinghua/CHA_MaleCouriers_NPC_01': { zh: '配送员B', en: 'Deliveryman B' },
  '25yinghua/CHA_predecessor_NPC_01': { zh: '货车前辈', en: 'Truck-senpai' },
  '27luoleilai/CHA_EngineerA_NPC_01': { zh: '白怀德', en: 'Dr. White' },
  '27luoleilai/CHA_ManagerB_NPC_01': { zh: '乔治', en: 'George' },
  '27luoleilai/CHA_ManagerB_NPC_02': { zh: '乔治年轻', en: 'George Young' },
  '27luoleilai/CHA_FacilitatorC_NPC_02': { zh: '瓦西尔监禁', en: 'Vasil Imprisoned' },
  '27luoleilai/CHA_FacilitatorC_NPC_01': { zh: '瓦西尔', en: 'Vasil' },
  '27luoleilai/CHA_FacilitatorC_NPC_03': { zh: '瓦西尔年轻', en: 'Vasil Young' },
  '27.5xiaan/CHA_CaptainKellen_NPC_02': { zh: '莫科什誓卫军D', en: 'Mokosh Guard D' },
  '27.5xiaan/CHA_CaptainKellen_NPC_03': { zh: '莫科什誓卫军E', en: 'Mokosh Guard E' },
  '27.5xiaan/CHA_CaptainKellen_NPC_04': { zh: '莫科什誓卫军F', en: 'Mokosh Guard F' },
  '28beisidi/CHA_NobleGuardian_01': { zh: '财团人形', en: 'Conglomerate Doll' },
  '29liushi/CHA_Yellow_GuardMale_01': { zh: '卫队成员男', en: 'Guard Member Male' },
  '29liushi/CHA_Pavel_01': { zh: '帕维尔', en: 'Pavel（帕维尔）' },
  '29liushi/CHA_Pegaso_01': { zh: '珀伽索', en: 'Pegasus' },
  '31heishandian/CHA_Commander2_01': { zh: '指挥官（男）', en: 'Commander (Male)' },
  '31heishandian/CHA_Commander2_02': { zh: '指挥官（女）', en: 'Commander (Female)' },
  '31heishandian/CHA_Commander1_01': { zh: '指挥官一代（男）', en: 'Commander Past (Male)' },
  '31heishandian/CHA_Commander1_02': { zh: '指挥官一代（女）', en: 'Commander Past (Female)' },
  '31heishandian/CHA_Researcher_01': { zh: '技术人员男', en: 'Technician Male' },
  '31heishandian/CHA_SoliderMale_01': { zh: '普通军人男', en: 'Soldier Male' },
  '31.5suopu/CHA_Krasso_01': { zh: '克拉索', en: 'Krassov' },
  '31.5suopu/CHA_Dragon_02': { zh: '乔扎（幼）', en: 'Jawza (Young)' },
  '31.5suopu/CHA_Dragon_01': { zh: '乔扎（幼）展翅', en: 'Jawza (Young) Spread Wings' },
  '31.5suopu/CHA_ArmedMale01_01': { zh: '官方武装人员男', en: 'Official Armed Forces Male' },
  '31.5suopu/CHA_ELID_01': { zh: '通用生骸', en: 'ELID' },
  '31.5suopu/CHA_PMCMale01_01': { zh: '雇佣兵男', en: 'Mercenary Male' },
  '31.5suopu/CHA_MedicalMale01_01': { zh: '医护人员男', en: 'Medical Staff Male' },
  '31.5suopu/CHA_SpecialAgentMale01_01': { zh: '特工男', en: 'Agent Male' },
  '32midier/CHA_Green_OldRichMale01_01': { zh: '白区老人男', en: 'White Zone Old Man' },
  '32midier/CHA_Green_OldNormalMale01_01': { zh: '绿区老人男', en: 'Green Zone Old Man' },
  '33fuling/CHA_Yellow_OldNormalMale01_01': { zh: '黄区老人男', en: 'Yellow Zone Old Man' },
  '33fuling/CHA_Snavel_01': { zh: '斯奈贝尔', en: 'Sneibel' },
  '33fuling/CHA_Strauss_01': { zh: '施特劳斯', en: 'Strauss' },
  '33fuling/CHA_WildHunt__01': { zh: '狂猎', en: 'Wild Hunt' },
  '34kelaida/CHA_Medquinn_01': { zh: '梅德', en: 'Mede' },
  '34kelaida/CHA_Medquinn_Suit_daily_02': { zh: '梅德常服', en: 'Mede Regular Clothes' },
  '34kelaida/CHA_Medquinn_Suit_daily_03': { zh: '梅德雨中', en: 'Mede In The Rain' },
  '34kelaida/CHA_FatOfficial1_01': { zh: '罗联官员胖男', en: 'Fat URNC Official' },
  '34kelaida/CHA_Lieutenant_NPC_01': { zh: '长城列车军上尉', en: 'Great Wall Railway Corps Captain' },
  '34kelaida/CHA_MaleVeteran01_01': { zh: '罗联军官老年男', en: 'Veteran URNC Officer' },
  '34kelaida/CHA_AdultWorker_01': { zh: '工人男', en: 'Worker Man' },
  '34kelaida/CHA_U_NPC_SP': { zh: '莱特一代', en: 'Light Past' },
  '32midier/CHA_PSAMale01_01': { zh: '白区工作人员男', en: 'White Zone Male Staff' },
  '34kelaida/CHA_Pose_01': { zh: '铁鲱', en: 'Iron Herring' },
  '34kelaida/CHA_Hunter_01': { zh: '斯派克', en: 'Spike' },
  '34kelaida/CHA_PSAMale_03': { zh: '治安管理部门男', en: 'PSA Male Officer' },
  '0ob/CHA_Poludnitsa_NPC_01': { zh: '佩妮泽', en: 'Poludnitsa' },
  '0ob/CHA_Nemesis_R_01': { zh: '纳美西丝R', en: 'Nemesis R' },
  '0ob/CHA_Nemesis_SR_01': { zh: '纳美西丝SR', en: 'Nemesis SR' },
  '0ob/CHA_Nemesis_Rest_01': { zh: '纳美西丝Rest', en: 'Nemesis Rest' },
  '4jiangyu/CHA_Nemesis_Paradeus_01': { zh: '纳美西丝Paradeus', en: 'Nemesis Paradeus' },
  '31heishandian/CHA_Nemesis_Gnosis_01': { zh: '纳美西丝SP', en: 'Nemesis SP' },
  '30liufenyi/CHA_IsomerN_01': { zh: '纳美西丝异构体', en: 'Nemesis Isomer' },
  '31.5suopu/CHA_Nemesis_Human_01': { zh: '纳美西丝人类', en: 'Nemesis Human' },
  '0ob/CHA_Peritya_SSR_01': { zh: '佩里缇亚SSR', en: 'Peritya SSR' },
  '0ob/CHA_Saga_NPC_01': { zh: '萨珈', en: 'Saga' },
  '0ob/CHA_Helianthus_NPC_01': { zh: '赫丽安图丝', en: 'Helianthus' },
  '1daiyan/CHA_Daiyan_SSR_01': { zh: '黛烟SSR', en: 'Daiyan SSR' },
  '0ob/CHA_Lind_SSR_01': { zh: '琳德SSR', en: 'Lind SSR' },
  '0ob/CHA_Mosinnagant_SSR_01': { zh: '莫辛纳甘SSR', en: 'Mosin-Nagant SSR' },
  '0ob/CHA_Springfield_NPC_01': { zh: '春田咖啡馆', en: 'Springfield Café' },
  '6wuerlide/CHA_Ullrid_SSR_01': { zh: '乌尔丽德SSR', en: 'Ullrid SSR' },
  '27luoleilai/CHA_Ullrid_Mask_01': { zh: '乌尔丽德面具', en: 'Ullrid Mask' },
  '6wuerlide/CHA_Lampetia_NPC_01': { zh: '兰珀蒂娅', en: 'Lambertia' },
  '9kelukai/CHA_Blusphere_NPC_01': { zh: '蓝雪球', en: 'Blusphere' },
  '9.5mishiti/CHA_Blusphere_NPC_02': { zh: '蓝雪球战损', en: 'Blusphere Damaged' },
  '13.5peili/CHA_Drachen_NPC_01': { zh: '德拉臣', en: 'Drachen' },
  '13chuntian/CHA_Springfield_NPC_SP': { zh: '春田少1', en: 'Springfield GF1' },
  '13.5peili/CHA_Springfield_SSR_01': { zh: '春田SSR', en: 'Springfield SSR' },
  '14qiuhua/CHA_Lenten_NPC_01': { zh: '兰汀', en: 'Lentine' },
  '24hailun/CHA_Lenten_NPC_02': { zh: '兰汀一代', en: 'Lentine Past' },
  '31.5suopu/CHA_Lenten_Suit_Protection_01': { zh: '兰汀防护服', en: 'Lentine Protective Suit' },
  '16nijita/CHA_Carmen_NPC_01': { zh: '卡门', en: 'Carmen' },
  '16nijita/CHA_Inessa_NPC_01': { zh: '伊涅萨', en: 'Inesa' },
  '17laiya/CHA_Cocoon_NPC_01': { zh: '茧', en: 'Cocoon' },
  '31.5suopu/CHA_Cocoon_Suit_levelup_01': { zh: '茧二阶段', en: 'Cocoon Second Stage' },
  '20linde/CHA_Seele_NPC_01': { zh: '希尔', en: 'Sier' },
  '20linde/CHA_Orphina_NPC_01': { zh: '奥尔菲娅', en: 'Orphia' },
  '20linde/CHA_Isha_NPC_01': { zh: '伊莎', en: 'Isa' },
  '21aifu/CHA_Voymastina_SSR_01': { zh: '威玛西娜SSR', en: 'Voymastina SSR' },
  '21aifu/CHA_Acicular_NPC_01': { zh: '针', en: 'Igla' },
  '24hailun/CHA_Acicular_Meta_01': { zh: '针兵器', en: 'Igla Weapon' },
  '21.5weimaxina/CHA_Voymastina_SSR_02': { zh: '威玛西娜机甲', en: 'Voymastina Mech' },
  '24hailun/CHA_Helen_SSR_01': { zh: '海伦SSR', en: 'Helen SSR' },
  '24hailun/CHA_Helen_Suit_01': { zh: '海伦一代', en: 'Helen Past' },
  '24hailun/CHA_Helen_SSR_02': { zh: '海伦礼服', en: 'Helen Dress' },
  '24hailun/CHA_Helen_Suit_02': { zh: '海伦曼尼安保', en: 'Helen Mangi Security' },
  '24hailun/CHA_Helen_Suit_03': { zh: '海伦摊牌', en: 'Helen Showdown' },
  '27luoleilai/CHA_Lorelei_SSR_01': { zh: '罗蕾莱SSR', en: 'Loreley SSR' },
  '27luoleilai/CHA_Lorelei_SSR_02': { zh: '罗蕾莱狱警', en: 'Loreley Prison Guard' },
  '29liushi/CHA_Liushi_01': { zh: '刘莳', en: 'Liushih' },
  '32midier/CHA_Sloane_01': { zh: '斯隆', en: 'Sloane' },
  '33fuling/CHA_M16_01': { zh: '白烨戈NPC', en: 'Beluga NPC' },
  '34kelaida/CHA_Ankyrie_01_Tactical': { zh: '安吉莉常服', en: 'Anjelie Tactical' },
  '34kelaida/CHA_Ankyrie_01': { zh: '安吉莉军装', en: 'Anjelie Military Uniform' },
  '34kelaida/CHA_Starvoid_02': { zh: '星渊（少女）', en: 'Star Abyss (Girl)' },
  '34kelaida/CHA_Shadowless_01': { zh: '夏朵利兹', en: 'Shadowless' },
  '34kelaida/CHA_kano_01': { zh: '卡诺', en: 'Kano' },
  '34kelaida/CHA_Blackmountain_01': { zh: '黑山雄鹰', en: 'Black Mountain Eagle' },
  '31heishandian/CHA_OTs-14_NPC_SP': { zh: '闪电一代', en: 'Groza Past' },
  '0ob/CHA_Groza_R_01': { zh: '闪电R', en: 'Groza R' },
  '0ob/CHA_Groza_SR_01': { zh: '闪电SR', en: 'Groza SR' },
  '0ob/CHA_Groza_Rest_01': { zh: '闪电Rest', en: 'Groza Rest' },
  '4jiangyu/CHA_Groza_Paradeus_01': { zh: '闪电Paradeus', en: 'Groza Paradeus' },
  '27luoleilai/CHA_Groza_Mask_01': { zh: '闪电面具', en: 'Groza Mask' },
  '31heishandian/CHA_Groza_Suit_Dress_01': { zh: '闪电礼服', en: 'Groza Dress' },
  '31heishandian/CHA_Groza_Losses_01': { zh: '闪电战损', en: 'Groza Damaged' },
  '0ob/CHA_Charolic_SSR_01': { zh: '克罗丽科SSR', en: 'Krolik SSR' },
  '0ob/CHA_Charolic_SR_01': { zh: '克罗丽科SR', en: 'Krolik SR' },
  '0ob/CHA_Charolic_Rest_01': { zh: '克罗丽科Rest', en: 'Krolik Rest' },
  '4jiangyu/CHA_Charolic_Paradeus_01': { zh: '克罗丽科Paradeus', en: 'Krolik Paradeus' },
  '27luoleilai/CHA_Charolic_Mask_01': { zh: '克罗丽科面具', en: 'Krolik Mask' },
  '14qiuhua/CHA_Dandelion_NPC_02': { zh: '丹德莱度假', en: 'Dandelion Vacation' },
  '30liufenyi/CHA_Dandely_Lose_01': { zh: '丹德莱炸毛', en: 'Dandelion Fried Hair' },
  '0ob/CHA_Lenna_SSR_01': { zh: '莱娜SSR', en: 'Lenna SSR' },
  '3laina/CHA_Lenna_SSR_02': { zh: '莱娜日常装', en: 'Lenna Casual' },
  '20linde/CHA_Lenna_Suit_01': { zh: '莱娜潜入装', en: 'Lenna Disguise' },
  '0ob/CHA_Levva_NPC_01': { zh: '莱娅西装', en: 'Leva Suit' },
  '0ob/CHA_Kalina_NPC_01': { zh: '格琳娜西装', en: 'Kalina Suit' },
  '4jiangyu/CHA_Nyto_NPC_01': { zh: '涅托', en: 'Nyto' },
  '0ob/CHA_Persicaria_NPC_01': { zh: '帕斯卡莉亚', en: 'Persica' },
  '0ob/CHA_Sexdwarf_NPC_01': { zh: '六分仪一形态', en: 'Sextans Form 1' },
  '4jiangyu/CHA_Sexdwarf_Paradeus_01': { zh: '六分仪一形态Paradeus', en: 'Sextans Form 1 Paradeus' },
  '30liufenyi/CHA_Sextans_01': { zh: '六分仪投放', en: 'Sextans Playable' },
  '0ob/CHA_Tololo_SSR_01': { zh: '托洛洛SSR', en: 'Tololo SSR' },
  '1daiyan/CHA_Zhaohui_SSR_01': { zh: '朝晖SSR', en: 'Zhaohui SSR' },
  '1daiyan/CHA_Jiangyu_SSR_01': { zh: '绛雨SSR', en: 'Jiangyu SSR' },
  '1daiyan/CHA_Macqiato_SSR_01': { zh: '玛绮朵SSR', en: 'Makiatto SSR' },
  '2sangduolaixi/CHA_Macqiato_SSR_02': { zh: '玛绮朵小熊', en: 'Makiatto Little Bear' },
  '0ob/CHA_Qiongjiu_SSR_01': { zh: '琼玖SSR', en: 'Qiongjiu SSR' },
  '0ob/CHA_Sabrina_SSR_01': { zh: '塞布丽娜SSR', en: 'Sabrina SSR' },
  '2sangduolaixi/CHA_Andoris_SSR_01': { zh: '安朵丝SSR', en: 'Andoris SSR' },
  '6wuerlide/CHA_Dusevnyj_SSR_01': { zh: '杜莎妮SSR', en: 'Dushevnaya SSR' },
  '24hailun/CHA_Dusevnyj_Suit_01': { zh: '杜莎妮一代', en: 'Dushevnaya Past' },
  '1daiyan/CHA_Esther_NPC_01': { zh: '埃丝特', en: 'Esther' },
  '6wuerlide/CHA_Rosaline_NPC_01': { zh: '罗莎琳', en: 'Rosalind' },
  '6wuerlide/CHA_RegularDoll_NPC_01': { zh: '普通人形', en: 'Regular Doll' },
  '8dushani/CHA_MAwomen_NPC_01': { zh: '中年女性', en: 'Middle-Aged Woman' },
  '10weiketuo/CHA_Koshmar_NPC_01': { zh: '喀什玛', en: 'Koshmar' },
  '9kelukai/CHA_Clukay_SSR_01': { zh: '可露凯SSR', en: 'Klukai SSR' },
  '10weiketuo/CHA_Vector_SSR_01': { zh: '维克托SSR', en: 'Vector SSR' },
  '15youxi/CHA_Yoohee_SSR_01': { zh: '幼熙SSR', en: 'Yoohee SSR' },
  '14qiuhua/CHA_Qiuhua_SSR_01': { zh: '秋桦SSR', en: 'Qiuhua SSR' },
  '16nijita/CHA_Nikita_SSR_01': { zh: '妮基塔SSR', en: 'Nikketa SSR' },
  '16nijita/CHA_Green_RichFemale01_NPC_01': { zh: '白区女性', en: 'White Zone Woman' },
  '16nijita/CHA_Green_NormalFemale01_NPC_01': { zh: '绿区女性', en: 'Green Zone Woman' },
  '16nijita/CHA_Yellow_NormalFemale01_NPC_01': { zh: '黄区女性', en: 'Yellow Zone Woman' },
  '17laiya/CHA_Levva_SSR_01': { zh: '莱娅SSR', en: 'Leva SSR' },
  '17laiya/CHA_Alf_SSR_01': { zh: '埃芙SSR', en: 'Alva SSR' },
  '34kelaida/CHA_Alva_Suit_01': { zh: '埃芙西装', en: 'Alva Suit' },
  '29liushi/CHA_Yellow_GuardFemale_01': { zh: '卫队成员女', en: 'Guard Member Female' },
  '17laiya/CHA_Robella_SSR_01': { zh: '洛贝拉SSR', en: 'Robella SSR' },
  '31.5suopu/CHA_Robella_Suit_GriffinUniform_01': { zh: '洛贝拉一代', en: 'Robella Past' },
  '17laiya/CHA_Sop_NPC_01': { zh: '索普NPC', en: 'Soppo NPC' },
  '31.5suopu/CHA_Soppo_02': { zh: '索普投放', en: 'Soppo Playable' },
  '31.5suopu/CHA_Soppo_GriffinUniform_01': { zh: '索普一代', en: 'Soppo Past' },
  '17.5luobeila/CHA_BlackGroza_NPC_01': { zh: '黑闪电', en: 'Black Groza' },
  '31heishandian/CHA_OTs-14_Wedding_01': { zh: '黑闪电婚纱', en: 'Black Groza Wedding Dress' },
  '31heishandian/CHA_OTs-14_02': { zh: '黑闪电战斗', en: 'Black Groza Battle' },
  '31heishandian/CHA_OTs-14_01': { zh: '黑闪电投放', en: 'Black Groza Playable' },
  '18laini/CHA_Lene_SSR_01': { zh: '莱妮SSR', en: 'Lainie SSR' },
  '18laini/CHA_Lene_Suit_ump40_01': { zh: '莱妮蝴蝶', en: 'Lainie Butterfly' },
  '18laini/CHA_Levva_Suit_ump45_01': { zh: '莱娅一代', en: 'Leva Past' },
  '18laini/CHA_Levva_Suit_ump45_02': { zh: '莱娅蝴蝶', en: 'Leva Butterfly' },
  '19fuluolun/CHA_WomanA_NPC_01': { zh: '埃斯梅', en: 'Esme' },
  '21aifu/CHA_Chiloveig_NPC_02': { zh: '奇洛薇格', en: 'Chiloveig' },
  '21aifu/CHA_Chiloveig_NPC_01': { zh: '奇洛薇格白大褂', en: 'Chiloveig White Coat' },
  '21aifu/CHA_Kalina_Suit_01': { zh: '格琳娜病服', en: 'Kalina Hospital Gown' },
  '31.5suopu/CHA_Kalina_Suit_Daily_01': { zh: '格琳娜休闲服', en: 'Kalina Casual' },
  '31.5suopu/CHA_Kalina_Suit_InvesGroup_01': { zh: '格琳娜防护服', en: 'Kalina Protective Suit' },
  '21aifu/CHA_Orpheoreon_NPC_01': { zh: '欧菲露妮研究员', en: 'Orphelune Research' },
  '21aifu/CHA_Orpheoreon_NPC_02': { zh: '欧菲露妮正装', en: 'Orphelune Formal' },
  '21aifu/CHA_Ange_NPC_01': { zh: '安洁莉娅', en: 'Angelia' },
  '21aifu/CHA_Ange_Suit_01': { zh: '安洁莉娅武装', en: 'Angelia Armed' },
  '34kelaida/CHA_Ange_NPC_SP': { zh: '安洁莉娅一代战损', en: 'Angelia Past Injured' },
  '21aifu/CHA_RPK-16_NPC_01': { zh: 'RPK-16', en: 'RPK-16' },
  '34kelaida/CHA_RPK16_NPC_SP': { zh: 'RPK-16一代', en: 'RPK-16 Past' },
  '21aifu/CHA_AK12_NPC_01': { zh: 'AK-12', en: 'AK-12' },
  '34kelaida/CHA_AK12_NPC_SP': { zh: '克莱妲一代战损', en: 'Koleda Past Damaged' },
  '23liuyisi/CHA_Beelneith_NPC_01': { zh: '贝欧尼斯', en: 'Beelneith' },
  '23liuyisi/CHA_PersicariaDoll_NPC_01': { zh: '人形帕斯卡', en: 'Persicaria Doll' },
  '23liuyisi/CHA_Lewis_SSR_01': { zh: '刘易斯SSR', en: 'Lewis SSR' },
  '24hailun/CHA_Bereifel_NPC_01': { zh: '贝瑞菲尔', en: 'Berryfield' },
  '24.5feitusa/CHA_Phaetusa_SSR_01': { zh: '翡图萨SSR', en: 'Phaetusa SSR' },
  '24.5feitusa/CHA_Sweeper_NPC_01': { zh: '清道夫', en: 'Sweeper' },
  '25yinghua/CHA_manager_NPC_01': { zh: '配送站站长', en: 'Delivery Station Manager' },
  '25yinghua/CHA_FemaleCouriers_NPC_01': { zh: '配送员A', en: 'Deliveryman A' },
  '27luoleilai/CHA_Sia_NPC_01': { zh: '希娅', en: 'Shea' },
  '27luoleilai/CHA_Gaia_NPC_01': { zh: '盖娅', en: 'Gaia' },
  '27.5xiaan/CHA_Yellow_FemaleWorker_01': { zh: '黄区女工', en: 'Yellow Zone Female Worker' },
  '28beisidi/CHA_Basti_01': { zh: '贝丝蒂', en: 'Basti' },
  '28beisidi/CHA_Lydia_01': { zh: '莉迪亚', en: 'Lydia' },
  '29liushi/CHA_Type56-1_01': { zh: '知穗NPC', en: 'Zhisui NPC' },
  '30liufenyi/CHA_MysteryWoman_NPC_01': { zh: '母亲', en: 'Mother' },
  '31.5suopu/CHA_Caldwell_01': { zh: '科德韦尔', en: 'Caldwell' },
  '31.5suopu/CHA_Caldwell_Teacher_01': { zh: '科德韦尔年轻', en: 'Caldwell Young' },
  '31.5suopu/CHA_Caldwell_Suit_Protection_01': { zh: '科德韦尔防护服', en: 'Caldwell Protective Suit' },
  '31.5suopu/CHA_Lisa_01': { zh: '丽萨', en: 'Lisa' },
  '31.5suopu/CHA_Nele_01': { zh: '奈乐', en: 'Nele' },
  '31heishandian/CHA_Cloak_Losses_01': { zh: '斗篷人', en: 'Cloaked Person' },
  '31heishandian/CHA_Researcher_02': { zh: '技术人员女', en: 'Technician Female' },
  '31heishandian/CHA_SoliderFemale_01': { zh: '普通军人女', en: 'Soldier Female' },
  '31.5suopu/CHA_PMCFemale01_01': { zh: '雇佣兵女', en: 'Mercenary Female' },
  '31.5suopu/CHA_ArmedFemale01_01': { zh: '官方武装人员女', en: 'Official Armed Forces Female' },
  '31.5suopu/CHA_MedicalFemale01_01': { zh: '医护人员女', en: 'Medical Staff Female' },
  '31.5suopu/CHA_SpecialAgentFemale01_01': { zh: '特工女', en: 'Agent Female' },
  '32midier/CHA_Mityl_01': { zh: '米蒂尔投放', en: 'Mityl Playable' },
  '32midier/CHA_Kuro_01': { zh: '卡萝NPC', en: 'Kuro NPC' },
  '32midier/CHA_Agatha_01': { zh: '阿加莎', en: 'Agatha' },
  '32midier/CHA_Bellis_01': { zh: '贝丽丝', en: 'Bellis' },
  '26weierde/CHA_Daria_NPC_01': { zh: '达莉娅', en: 'Daria' },
  '26weierde/CHA_Delilah_01': { zh: '黛拉', en: 'Della' },
  '32midier/CHA_Green_OldRichFemale01_01': { zh: '白区老人女', en: 'White Zone Old Woman' },
  '32midier/CHA_Green_OldNormalFemale01_01': { zh: '绿区老人女', en: 'Green Zone Old Woman' },
  '33fuling/CHA_Yellow_OldNormalFemale01_01': { zh: '黄区老人女', en: 'Yellow Zone Old Woman' },
  '33fuling/CHA_Anonymous_01': { zh: '米卡', en: 'Mika' },
  '34kelaida/CHA_Koleda_01': { zh: '克莱妲投放', en: 'Koleda Playable' },
  '34kelaida/CHA_Friday_01': { zh: '星期五闭眼', en: 'Friday Closed Eyes' },
  '34kelaida/CHA_Friday_SuitOpen eyes_01': { zh: '星期五睁眼', en: 'Friday Open Eyes' },
  '34kelaida/CHA_Friday_SuitBroken_01': { zh: '星期五战损闭眼', en: 'Friday Damaged Closed Eyes' },
  '34kelaida/CHA_Friday_SuitBroken_02': { zh: '星期五战损睁眼', en: 'Friday Damaged Open Eyes' },
  '34kelaida/CHA_Narcissus_01': { zh: '水仙花', en: 'Narcissus' },
  '34kelaida/CHA_Koleda_NPC_SP': { zh: '克莱妲一代涅托', en: 'Koleda Past Nyto' },
  '34kelaida/CHA_Mechelin_01': { zh: '萨德', en: 'Sade' },
  '34kelaida/CHA_PSAFemale_03': { zh: '治安管理部门女', en: 'PSA Female Officer' },
  '34kelaida/CHA_PSAFemale_02': { zh: '非军管女', en: 'Non-Military Woman' },
  '0ob/CHA_Mayling_NPC_01': { zh: '美玲', en: 'Mayling' },
  '0ob/CHA_Colphne_N_01': { zh: '寇尔芙N', en: 'Colphne N' },
  '0ob/CHA_Colphne_SR_01': { zh: '寇尔芙SR', en: 'Colphne SR' },
  '0ob/CHA_Colphne_Rest_01': { zh: '寇尔芙Rest', en: 'Colphne Rest' },
  '2sangduolaixi/CHA_Colphne_Paradeus_01': { zh: '寇尔芙Paradeus', en: 'Colphne Paradeus' },
  '31heishandian/CHA_Darture_Losses_01': { zh: '黑眼战损', en: 'Darture Damaged' },
  '0ob/CHA_Darcular_NPC_01': { zh: '黑眼一形态', en: 'Darture Form 1' },
  '0ob/CHA_Helena_NPC_01': { zh: '海伦娜', en: 'Helena' },
  '4jiangyu/CHA_Helena_Paradeus_01': { zh: '海伦娜Paradeus', en: 'Helena Paradeus' },
  '2sangduolaixi/CHA_Niter_NPC_01': { zh: '妮特', en: 'Niter' },
  '0ob/CHA_Vepley_SR_01': { zh: '维普蕾SR', en: 'Vepley SR' },
  '0ob/CHA_Vepley_SSR_01': { zh: '维普蕾SSR', en: 'Vepley SSR' },
  '0ob/CHA_Vepley_Rest_01': { zh: '维普蕾Rest', en: 'Vepley Rest' },
  '4jiangyu/CHA_Vepley_Paradeus_01': { zh: '维普蕾Paradeus', en: 'Vepley Paradeus' },
  '0ob/CHA_Nagant_SR_01': { zh: '纳甘SR', en: 'Nagant SR' },
  '0ob/CHA_Sharkry_SR_01': { zh: '夏克里SR', en: 'Sharkry SR' },
  '0ob/CHA_Sharkry_SSR_01': { zh: '夏克里SSR', en: 'Sharkry SSR' },
  '0ob/CHA_Cheeta_SR_01': { zh: '奇塔SR', en: 'Cheeta SR' },
  '0ob/CHA_Centaureissi_SSR_01': { zh: '桑朵莱希SSR', en: 'Centaureissi SSR' },
  '0ob/CHA_Ksenia_SR_01': { zh: '科谢尼娅SR', en: 'Ksenia SR' },
  '6wuerlide/CHA_Papasha_SSR_01': { zh: '波波沙SSR', en: 'Papasha SSR' },
  '6wuerlide/CHA_Littara_SR_01': { zh: '莉塔拉SR', en: 'Littara SR' },
  '6wuerlide/CHA_Suomi_SSR_01': { zh: '索米SSR', en: 'Suomi SSR' },
  '27luoleilai/CHA_Suomi_Mask_01': { zh: '索米面具', en: 'Suomi Mask' },
  '6wuerlide/CHA_Bathilda_NPC_01': { zh: '巴希达', en: 'Bathilde' },
  '6wuerlide/CHA_Lotta_SR_01': { zh: '洛塔SR', en: 'Lotta SR' },
  '9kelukai/CHA_Biyoca_SSR_01': { zh: '比悠卡SSR', en: 'Belka SSR' },
  '9kelukai/CHA_Mechty_SSR_01': { zh: '米什缇SSR', en: 'Mechty SSR' },
  '7suomi/CHA_Suomi_Rest_01': { zh: '索米Rest', en: 'Suomi Rest' },
  '10weiketuo/CHA_Ruchey_SSR_01': { zh: '乌琪SSR', en: 'Ruchey SSR' },
  '10weiketuo/CHA_Harpsy_SSR_01': { zh: '哈卜茜SSR', en: 'Harpsy SSR' },
  '10weiketuo/CHA_Welrod_SSR_01': { zh: '维尔德SSR', en: 'Welrod SSR' },
  '13.5peili/CHA_Aminda_NPC_01': { zh: '阿米达', en: 'Aminda' },
  '15youxi/CHA_Lumi_NPC_01': { zh: '卢米', en: 'Lumi' },
  '13chuntian/CHA_Peri_SSR_01': { zh: '佩莉SSR', en: 'Peri SSR' },
  '13chuntian/CHA_Mopro1.5_NPC_01': { zh: '莫普1.5', en: 'Mopro 1.5' },
  '13.5peili/CHA_Faye_SSR_01': { zh: '绯SSR', en: 'Faye SSR' },
  '14qiuhua/CHA_Helena_NPC_02': { zh: '海伦娜附体', en: 'Helena Possessed' },
  '14qiuhua/CHA_Helena_NPC_03': { zh: '海伦娜D68', en: 'Helena D68' },
  '16nijita/CHA_Green_RichBoy01_NPC_01': { zh: '白区男孩', en: 'White Zone Boy' },
  '16nijita/CHA_Green_RichGirl01_NPC_01': { zh: '白区女孩', en: 'White Zone Girl' },
  '16nijita/CHA_Green_NormalBoy01_NPC_01': { zh: '绿区男孩', en: 'Green Zone Boy' },
  '16nijita/CHA_Green_NormalGirl01_NPC_01': { zh: '绿区女孩', en: 'Green Zone Girl' },
  '16nijita/CHA_Yellow_NormalBoy01_NPC_01': { zh: '黄区男孩', en: 'Yellow Zone Boy' },
  '16nijita/CHA_Yellow_NormalGirl01_NPC_01': { zh: '黄区女孩', en: 'Yellow Zone Girl' },
  '17laiya/CHA_G11_Suit_MaidUniform': { zh: 'G11女仆', en: 'G11 Maid' },
  '17laiya/CHA_Laibnis_NPC_01': { zh: '莱布妮丝', en: 'Leibnys' },
  '31.5suopu/CHA_Laibnis_Suit_InvesGroup_01': { zh: '莱布妮丝防护服', en: 'Leibnys Protective Suit' },
  '18laini/CHA_UnsearchableGirl_NPC_01': { zh: '神秘女孩', en: 'Mysterious Girl' },
  '19fuluolun/CHA_Florence_SSR_01': { zh: '芙洛伦SSR', en: 'Florence SSR' },
  '20linde/CHA_Elnida_NPC_01': { zh: '艾琳达', en: 'Elinda' },
  '21.5weimaxina/CHA_Bathilda_SSR_01': { zh: '巴希达SSR', en: 'Bathilde SSR' },
  '21.5weimaxina/CHA_Orpheoreon_Kid_01': { zh: '欧菲露妮幼年', en: 'Orphelune Childhood' },
  '24hailun/CHA_Heli_NPC_01': { zh: '赫利', en: 'Heli' },
  '25yinghua/CHA_Sakura_SSR_01': { zh: '樱花SSR', en: 'Sakura SSR' },
  '25yinghua/CHA_Sakura_NPC_01': { zh: '樱花快递员', en: 'Sakura Courier' },
  '27.5xiaan/CHA_Cheyanne_01': { zh: '夏安', en: 'Cheyanne' },
  '27.5xiaan/CHA_Cheyanne_02': { zh: '夏安战损', en: 'Cheyanne Damaged' },
  '27.5xiaan/CHA_Cheyanne_03': { zh: '夏安仓管', en: 'Cheyanne Warehouse' },
  '28beisidi/CHA_Ada_01': { zh: '佐伊', en: 'Zoe' },
  '28beisidi/CHA_G41_01': { zh: '芙铃', en: 'Faelynn' },
  '33fuling/CHA_Fuchin_01': { zh: '芙铃投放', en: 'Faelynn Playable' },
  '29liushi/CHA_Vera_01': { zh: '薇拉', en: 'Vera' },
  '30liufenyi/CHA_Starvoid_01': { zh: '星渊（幼）', en: 'Star Abyss (Young)' },
  '26weierde/CHA_Misia_NPC_01': { zh: '米希亚', en: 'Misia' },
  '34kelaida/CHA_Liberty_01': { zh: '罗贝蒂工程师', en: 'Liberty Engineer' },
  '34kelaida/CHA_Liberty_02': { zh: '罗贝蒂曼尼安保', en: 'Liberty Mangi Security' },
  '34kelaida/CHA_YoungWorker_01': { zh: '工人少年', en: 'Worker Young' },
  '34kelaida/CHA_Idestam_01': { zh: '苏维', en: 'Suvi' },
  'scrapyard/CHA_Dandelion_NPC_01': { zh: '丹德莱', en: 'Dandelion' },
  'scrapyard/CHA_Lene_SSR_01': { zh: '莱妮SSR（老）', en: 'Lainie SSR (outdated)' },
  'scrapyard/CHA_Levva_NPC_01': { zh: '莱娅西装（老）', en: 'Leva Suit (outdated)' },
  'scrapyard/CHA_Kalina_NPC_01': { zh: '格琳娜西装（老）', en: 'Kalina Suit (outdated)' },
};

/**
 * Utility to normalize a model id so overrides are matched reliably.
 */
export function normalizeModelId(id: string): string {
  if (!id) {
    return '';
  }
  return id.replace(/\\/g, '/');
}
